# file: .github/workflows/vlang-build-pipeline.yml
name: vlang-build-pipeline

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Build repository app
      run: v -o vlogql -prod vlogql.v
#    - name: Run V tests
#      run: v test .
    - name: Retrieve v.mod version
      run: |
        echo ::set-env name=TAG_NAME::$(cat v.mod | grep version | awk -F"'" '{print $2}')
    - name: NFPM DEB
      if: github.event_name != 'pull_request'
      uses: skynet-core/nfpm@v1.4
      id: deb-package
      with:
       target: vlogql_v${{ env.TAG_NAME }}.deb
       config: "vlogql.yaml"
       packager: "deb"
    - name: NFPM RPM
      if: github.event_name != 'pull_request'
      uses: skynet-core/nfpm@v1.4
      id: rpm-package
      with:
       target: vlogql_v${{ env.TAG_NAME }}.rpm
       config: "vlogql.yaml"
       packager: "rpm"
    - name: Get Time
      if: github.event_name != 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            vlogql
            vlogql_v${{ env.TAG_NAME }}.deb
            vlogql_v${{ env.TAG_NAME }}.rpm
        tag_name: v${{ steps.time.outputs.time }}
        release_name: vlogql_v${{ env.TAG_NAME }}_${{ steps.time.outputs.time }}
        draft: false
        prerelease: false
        overwrite: true
